services:
  # Serviço Web para a API com Docker (inclui FFmpeg)
  - type: web
    name: youtube-scraper-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: DOWNLOAD_DIR
        value: /app/downloads
    disk:
      name: downloads
      mountPath: /app/downloads
      sizeGB: 1