services:
  # Serviço Web para a API
  - type: web
    name: youtube-scraper-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: DOWNLOAD_DIR
        value: /opt/render/project/src/downloads
    disk:
      name: downloads
      mountPath: /opt/render/project/src/downloads
      sizeGB: 1
